sudo: required
services: 
    - docker

before_install: 
    - docker build -t docker-react -f Dockerfile.dev .
    
script: 
    - docker run -e CI=true docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker1"
    env: "docker1-env"
    bucket_name: "elasticbeanstalk-us-east-2-972411068204"
    bucket_path: "docker1"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"